# Generated by Django 2.2 on 2019-04-02 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='farmbusiness',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='farm_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmbusiness',
            name='liasons',
            field=models.ManyToManyField(blank=True, related_name='farm_liason', to=settings.AUTH_USER_MODEL),
        ),
    ]
